config/routes.rb
Rails.application.routes.draw do

  resources :hourly_histograms
  resources :monthly_histograms
  resources :weekly_histograms
  resources :daily_histograms
  resources :batch_histograms

  get 'friends/index'
  get 'tweets/view'
  get 'tweets/index'
  get 'batches/index'
  get 'twitter_users/profile/:id'  => 'twitter_users#profile'
  get 'twitter_users/graph/:id'    => 'twitter_users#graph'
  get 'twitter_users/:id/befriend' => 'twitter_users#befriend'
  get 'twitter_users/:id/defriend' => 'twitter_users#defriend'
  get 'twitter_users/lists/:id/:list'        => 'twitter_users#update_list'
  get 'twitter_users/lists/:id/:list/delete' => 'twitter_users#downdate_list'
end

app/models/hourly_histogram.rb
class HourlyHistogram < ActiveRecord::Base
end

app/controllers/hourly_histograms_controller.rb
class HourlyHistogramsController < ApplicationController
  before_action :set_hourly_histogram, only: [:show, :edit, :update, :destroy]

  # GET /hourly_histograms
  # GET /hourly_histograms.json
  def index
    @hourly_histograms = HourlyHistogram.all
  end

  # GET /hourly_histograms/1
  # GET /hourly_histograms/1.json
  def show
  end

  # GET /hourly_histograms/new
  def new
    @hourly_histogram = HourlyHistogram.new
  end

  # GET /hourly_histograms/1/edit
  def edit
  end

  # POST /hourly_histograms
  # POST /hourly_histograms.json
  def create
    @hourly_histogram = HourlyHistogram.new(hourly_histogram_params)

    respond_to do |format|
      if @hourly_histogram.save
        format.html { redirect_to @hourly_histogram, notice: 'Hourly histogram was successfully created.' }
        format.json { render :show, status: :created, location: @hourly_histogram }
      else
        format.html { render :new }
        format.json { render json: @hourly_histogram.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hourly_histograms/1
  # PATCH/PUT /hourly_histograms/1.json
  def update
    respond_to do |format|
      if @hourly_histogram.update(hourly_histogram_params)
        format.html { redirect_to @hourly_histogram, notice: 'Hourly histogram was successfully updated.' }
        format.json { render :show, status: :ok, location: @hourly_histogram }
      else
        format.html { render :edit }
        format.json { render json: @hourly_histogram.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hourly_histograms/1
  # DELETE /hourly_histograms/1.json
  def destroy
    @hourly_histogram.destroy
    respond_to do |format|
      format.html { redirect_to hourly_histograms_url, notice: 'Hourly histogram was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hourly_histogram
      @hourly_histogram = HourlyHistogram.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hourly_histogram_params
      params.require(:hourly_histogram).permit(:name, :tweet_count, :since_id, :histogram, :metric, :stream)
    end
end

app/helpers/hourly_histograms_helper.rb
module HourlyHistogramsHelper
end

app/views/hourly_histograms/_form.html.erb
<%= form_for(@hourly_histogram) do |f| %>
  <% if @hourly_histogram.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hourly_histogram.errors.count, "error") %> prohibited this hourly_histogram from being saved:</h2>

      <ul>
      <% @hourly_histogram.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tweet_count %><br>
    <%= f.number_field :tweet_count %>
  </div>
  <div class="field">
    <%= f.label :since_id %><br>
    <%= f.number_field :since_id %>
  </div>
  <div class="field">
    <%= f.label :histogram %><br>
    <%= f.text_area :histogram %>
  </div>
  <div class="field">
    <%= f.label :metric %><br>
    <%= f.text_field :metric %>
  </div>
  <div class="field">
    <%= f.label :stream %><br>
    <%= f.text_field :stream %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hourly_histograms/edit.html.erb
<h1>Editing hourly_histogram</h1>

<%= render 'form' %>

<%= link_to 'Show', @hourly_histogram %> |
<%= link_to 'Back', hourly_histograms_path %>

app/views/hourly_histograms/index.html.erb
<h1>Listing hourly_histograms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Tweet count</th>
      <th>Since</th>
      <th>Histogram</th>
      <th>Metric</th>
      <th>Stream</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hourly_histograms.each do |hourly_histogram| %>
      <tr>
        <td><%= hourly_histogram.name %></td>
        <td><%= hourly_histogram.tweet_count %></td>
        <td><%= hourly_histogram.since_id %></td>
        <td><%= hourly_histogram.histogram %></td>
        <td><%= hourly_histogram.metric %></td>
        <td><%= hourly_histogram.stream %></td>
        <td><%= link_to 'Show', hourly_histogram %></td>
        <td><%= link_to 'Edit', edit_hourly_histogram_path(hourly_histogram) %></td>
        <td><%= link_to 'Destroy', hourly_histogram, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hourly histogram', new_hourly_histogram_path %>

app/views/hourly_histograms/new.html.erb
<h1>New hourly_histogram</h1>

<%= render 'form' %>

<%= link_to 'Back', hourly_histograms_path %>

app/views/hourly_histograms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hourly_histogram.name %>
</p>

<p>
  <strong>Tweet count:</strong>
  <%= @hourly_histogram.tweet_count %>
</p>

<p>
  <strong>Since:</strong>
  <%= @hourly_histogram.since_id %>
</p>

<p>
  <strong>Histogram:</strong>
  <%= @hourly_histogram.histogram %>
</p>

<p>
  <strong>Metric:</strong>
  <%= @hourly_histogram.metric %>
</p>

<p>
  <strong>Stream:</strong>
  <%= @hourly_histogram.stream %>
</p>

<%= link_to 'Edit', edit_hourly_histogram_path(@hourly_histogram) %> |
<%= link_to 'Back', hourly_histograms_path %>