config/routes.rb
Rails.application.routes.draw do

  resources :hourly_histograms
  resources :monthly_histograms
  resources :weekly_histograms
  resources :daily_histograms
  resources :batch_histograms

  get 'friends/index'
  get 'tweets/view'
  get 'tweets/index'
  get 'batches/index'
  get 'twitter_users/profile/:id'  => 'twitter_users#profile'
  get 'twitter_users/graph/:id'    => 'twitter_users#graph'
  get 'twitter_users/:id/befriend' => 'twitter_users#befriend'
  get 'twitter_users/:id/defriend' => 'twitter_users#defriend'
  get 'twitter_users/lists/:id/:list'        => 'twitter_users#update_list'
  get 'twitter_users/lists/:id/:list/delete' => 'twitter_users#downdate_list'
end

app/models/weekly_histogram.rb
class WeeklyHistogram < ActiveRecord::Base
end

app/controllers/weekly_histograms_controller.rb
class WeeklyHistogramsController < ApplicationController
  before_action :set_weekly_histogram, only: [:show, :edit, :update, :destroy]

  # GET /weekly_histograms
  # GET /weekly_histograms.json
  def index
    @weekly_histograms = WeeklyHistogram.all
  end

  # GET /weekly_histograms/1
  # GET /weekly_histograms/1.json
  def show
  end

  # GET /weekly_histograms/new
  def new
    @weekly_histogram = WeeklyHistogram.new
  end

  # GET /weekly_histograms/1/edit
  def edit
  end

  # POST /weekly_histograms
  # POST /weekly_histograms.json
  def create
    @weekly_histogram = WeeklyHistogram.new(weekly_histogram_params)

    respond_to do |format|
      if @weekly_histogram.save
        format.html { redirect_to @weekly_histogram, notice: 'Weekly histogram was successfully created.' }
        format.json { render :show, status: :created, location: @weekly_histogram }
      else
        format.html { render :new }
        format.json { render json: @weekly_histogram.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weekly_histograms/1
  # PATCH/PUT /weekly_histograms/1.json
  def update
    respond_to do |format|
      if @weekly_histogram.update(weekly_histogram_params)
        format.html { redirect_to @weekly_histogram, notice: 'Weekly histogram was successfully updated.' }
        format.json { render :show, status: :ok, location: @weekly_histogram }
      else
        format.html { render :edit }
        format.json { render json: @weekly_histogram.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weekly_histograms/1
  # DELETE /weekly_histograms/1.json
  def destroy
    @weekly_histogram.destroy
    respond_to do |format|
      format.html { redirect_to weekly_histograms_url, notice: 'Weekly histogram was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weekly_histogram
      @weekly_histogram = WeeklyHistogram.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weekly_histogram_params
      params.require(:weekly_histogram).permit(:name, :tweet_count, :since_id, :histogram, :metric, :stream)
    end
end

app/helpers/weekly_histograms_helper.rb
module WeeklyHistogramsHelper
end

app/views/weekly_histograms/_form.html.erb
<%= form_for(@weekly_histogram) do |f| %>
  <% if @weekly_histogram.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@weekly_histogram.errors.count, "error") %> prohibited this weekly_histogram from being saved:</h2>

      <ul>
      <% @weekly_histogram.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tweet_count %><br>
    <%= f.number_field :tweet_count %>
  </div>
  <div class="field">
    <%= f.label :since_id %><br>
    <%= f.number_field :since_id %>
  </div>
  <div class="field">
    <%= f.label :histogram %><br>
    <%= f.text_area :histogram %>
  </div>
  <div class="field">
    <%= f.label :metric %><br>
    <%= f.text_field :metric %>
  </div>
  <div class="field">
    <%= f.label :stream %><br>
    <%= f.text_field :stream %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/weekly_histograms/edit.html.erb
<h1>Editing weekly_histogram</h1>

<%= render 'form' %>

<%= link_to 'Show', @weekly_histogram %> |
<%= link_to 'Back', weekly_histograms_path %>

app/views/weekly_histograms/index.html.erb
<h1>Listing weekly_histograms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Tweet count</th>
      <th>Since</th>
      <th>Histogram</th>
      <th>Metric</th>
      <th>Stream</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @weekly_histograms.each do |weekly_histogram| %>
      <tr>
        <td><%= weekly_histogram.name %></td>
        <td><%= weekly_histogram.tweet_count %></td>
        <td><%= weekly_histogram.since_id %></td>
        <td><%= weekly_histogram.histogram %></td>
        <td><%= weekly_histogram.metric %></td>
        <td><%= weekly_histogram.stream %></td>
        <td><%= link_to 'Show', weekly_histogram %></td>
        <td><%= link_to 'Edit', edit_weekly_histogram_path(weekly_histogram) %></td>
        <td><%= link_to 'Destroy', weekly_histogram, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Weekly histogram', new_weekly_histogram_path %>

app/views/weekly_histograms/new.html.erb
<h1>New weekly_histogram</h1>

<%= render 'form' %>

<%= link_to 'Back', weekly_histograms_path %>

app/views/weekly_histograms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @weekly_histogram.name %>
</p>

<p>
  <strong>Tweet count:</strong>
  <%= @weekly_histogram.tweet_count %>
</p>

<p>
  <strong>Since:</strong>
  <%= @weekly_histogram.since_id %>
</p>

<p>
  <strong>Histogram:</strong>
  <%= @weekly_histogram.histogram %>
</p>

<p>
  <strong>Metric:</strong>
  <%= @weekly_histogram.metric %>
</p>

<p>
  <strong>Stream:</strong>
  <%= @weekly_histogram.stream %>
</p>

<%= link_to 'Edit', edit_weekly_histogram_path(@weekly_histogram) %> |
<%= link_to 'Back', weekly_histograms_path %>