config/routes.rb
Rails.application.routes.draw do

  resources :hourly_histograms
  resources :monthly_histograms
  resources :weekly_histograms
  resources :daily_histograms
  resources :batch_histograms

  get 'friends/index'
  get 'tweets/view'
  get 'tweets/index'
  get 'batches/index'
  get 'twitter_users/profile/:id'  => 'twitter_users#profile'
  get 'twitter_users/graph/:id'    => 'twitter_users#graph'
  get 'twitter_users/:id/befriend' => 'twitter_users#befriend'
  get 'twitter_users/:id/defriend' => 'twitter_users#defriend'
  get 'twitter_users/lists/:id/:list'        => 'twitter_users#update_list'
  get 'twitter_users/lists/:id/:list/delete' => 'twitter_users#downdate_list'
end

app/models/batch_histogram.rb
class BatchHistogram < ActiveRecord::Base
end

app/controllers/batch_histograms_controller.rb
class BatchHistogramsController < ApplicationController
  before_action :set_batch_histogram, only: [:show, :edit, :update, :destroy]

  # GET /batch_histograms
  # GET /batch_histograms.json
  def index
    @batch_histograms = BatchHistogram.all
  end

  # GET /batch_histograms/1
  # GET /batch_histograms/1.json
  def show
  end

  # GET /batch_histograms/new
  def new
    @batch_histogram = BatchHistogram.new
  end

  # GET /batch_histograms/1/edit
  def edit
  end

  # POST /batch_histograms
  # POST /batch_histograms.json
  def create
    @batch_histogram = BatchHistogram.new(batch_histogram_params)

    respond_to do |format|
      if @batch_histogram.save
        format.html { redirect_to @batch_histogram, notice: 'Batch histogram was successfully created.' }
        format.json { render :show, status: :created, location: @batch_histogram }
      else
        format.html { render :new }
        format.json { render json: @batch_histogram.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /batch_histograms/1
  # PATCH/PUT /batch_histograms/1.json
  def update
    respond_to do |format|
      if @batch_histogram.update(batch_histogram_params)
        format.html { redirect_to @batch_histogram, notice: 'Batch histogram was successfully updated.' }
        format.json { render :show, status: :ok, location: @batch_histogram }
      else
        format.html { render :edit }
        format.json { render json: @batch_histogram.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /batch_histograms/1
  # DELETE /batch_histograms/1.json
  def destroy
    @batch_histogram.destroy
    respond_to do |format|
      format.html { redirect_to batch_histograms_url, notice: 'Batch histogram was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_batch_histogram
      @batch_histogram = BatchHistogram.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def batch_histogram_params
      params.require(:batch_histogram).permit(:name, :tweet_count, :since_id, :histogram, :metric)
    end
end

app/helpers/batch_histograms_helper.rb
module BatchHistogramsHelper
end

app/views/batch_histograms/_form.html.erb
<%= form_for(@batch_histogram) do |f| %>
  <% if @batch_histogram.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@batch_histogram.errors.count, "error") %> prohibited this batch_histogram from being saved:</h2>

      <ul>
      <% @batch_histogram.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tweet_count %><br>
    <%= f.number_field :tweet_count %>
  </div>
  <div class="field">
    <%= f.label :since_id %><br>
    <%= f.number_field :since_id %>
  </div>
  <div class="field">
    <%= f.label :histogram %><br>
    <%= f.text_area :histogram %>
  </div>
  <div class="field">
    <%= f.label :metric %><br>
    <%= f.text_field :metric %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/batch_histograms/edit.html.erb
<h1>Editing batch_histogram</h1>

<%= render 'form' %>

<%= link_to 'Show', @batch_histogram %> |
<%= link_to 'Back', batch_histograms_path %>

app/views/batch_histograms/index.html.erb
<h1>Listing batch_histograms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Datetime</th>
      <th>&nbsp;</th>
      <th>Tweet count</th>
      <th>Histogram</th>
      <th>Metric</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @batch_histograms.each do |batch_histogram| %>
      <tr>
        <td><%= batch_histogram.name %></td>
        <td><%= batch_histogram.created_at %></td>
	<td>&nbsp;</td>
        <td><%= batch_histogram.tweet_count %></td>
        <td><%= batch_histogram.histogram.size %></td>
        <td><%= batch_histogram.metric %></td>
        <td><%= link_to 'Show', batch_histogram %></td>
        <td><%= link_to 'Edit', edit_batch_histogram_path(batch_histogram) %></td>
        <td><%= link_to 'Destroy', batch_histogram, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Batch histogram', new_batch_histogram_path %>

app/views/batch_histograms/new.html.erb
<h1>New batch_histogram</h1>

<%= render 'form' %>

<%= link_to 'Back', batch_histograms_path %>

app/views/batch_histograms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @batch_histogram.name %>
</p>

<p>
  <strong>Tweet count:</strong>
  <%= @batch_histogram.tweet_count %>
</p>

<p>
  <strong>Since:</strong>
  <%= @batch_histogram.since_id %>
</p>

<p>
  <strong>Histogram:</strong>
  <%= @batch_histogram.histogram %>
</p>

<p>
  <strong>Metric:</strong>
  <%= @batch_histogram.metric %>
</p>

<%= link_to 'Edit', edit_batch_histogram_path(@batch_histogram) %> |
<%= link_to 'Back', batch_histograms_path %>