config/routes.rb
Rails.application.routes.draw do

  resources :hourly_histograms
  resources :monthly_histograms
  resources :weekly_histograms
  resources :daily_histograms
  resources :batch_histograms

  get 'friends/index'
  get 'tweets/view'
  get 'tweets/index'
  get 'batches/index'
  get 'twitter_users/profile/:id'  => 'twitter_users#profile'
  get 'twitter_users/graph/:id'    => 'twitter_users#graph'
  get 'twitter_users/:id/befriend' => 'twitter_users#befriend'
  get 'twitter_users/:id/defriend' => 'twitter_users#defriend'
  get 'twitter_users/lists/:id/:list'        => 'twitter_users#update_list'
  get 'twitter_users/lists/:id/:list/delete' => 'twitter_users#downdate_list'
end

app/models/daily_histogram.rb
class DailyHistogram < ActiveRecord::Base
end

app/controllers/daily_histograms_controller.rb
class DailyHistogramsController < ApplicationController
  before_action :set_daily_histogram, only: [:show, :edit, :update, :destroy]

  # GET /daily_histograms
  # GET /daily_histograms.json
  def index
    @daily_histograms = DailyHistogram.all
  end

  # GET /daily_histograms/1
  # GET /daily_histograms/1.json
  def show
  end

  # GET /daily_histograms/new
  def new
    @daily_histogram = DailyHistogram.new
  end

  # GET /daily_histograms/1/edit
  def edit
  end

  # POST /daily_histograms
  # POST /daily_histograms.json
  def create
    @daily_histogram = DailyHistogram.new(daily_histogram_params)

    respond_to do |format|
      if @daily_histogram.save
        format.html { redirect_to @daily_histogram, notice: 'Daily histogram was successfully created.' }
        format.json { render :show, status: :created, location: @daily_histogram }
      else
        format.html { render :new }
        format.json { render json: @daily_histogram.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /daily_histograms/1
  # PATCH/PUT /daily_histograms/1.json
  def update
    respond_to do |format|
      if @daily_histogram.update(daily_histogram_params)
        format.html { redirect_to @daily_histogram, notice: 'Daily histogram was successfully updated.' }
        format.json { render :show, status: :ok, location: @daily_histogram }
      else
        format.html { render :edit }
        format.json { render json: @daily_histogram.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /daily_histograms/1
  # DELETE /daily_histograms/1.json
  def destroy
    @daily_histogram.destroy
    respond_to do |format|
      format.html { redirect_to daily_histograms_url, notice: 'Daily histogram was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_daily_histogram
      @daily_histogram = DailyHistogram.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def daily_histogram_params
      params.require(:daily_histogram).permit(:name, :tweet_count, :since_id, :histogram, :metric, :stream)
    end
end

app/helpers/daily_histograms_helper.rb
module DailyHistogramsHelper
end

app/views/daily_histograms/_form.html.erb
<%= form_for(@daily_histogram) do |f| %>
  <% if @daily_histogram.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@daily_histogram.errors.count, "error") %> prohibited this daily_histogram from being saved:</h2>

      <ul>
      <% @daily_histogram.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tweet_count %><br>
    <%= f.number_field :tweet_count %>
  </div>
  <div class="field">
    <%= f.label :since_id %><br>
    <%= f.number_field :since_id %>
  </div>
  <div class="field">
    <%= f.label :histogram %><br>
    <%= f.text_area :histogram %>
  </div>
  <div class="field">
    <%= f.label :metric %><br>
    <%= f.text_field :metric %>
  </div>
  <div class="field">
    <%= f.label :stream %><br>
    <%= f.text_field :stream %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/daily_histograms/edit.html.erb
<h1>Editing daily_histogram</h1>

<%= render 'form' %>

<%= link_to 'Show', @daily_histogram %> |
<%= link_to 'Back', daily_histograms_path %>

app/views/daily_histograms/index.html.erb
<h1>Listing daily_histograms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Tweet count</th>
      <th>Since</th>
      <th>Histogram</th>
      <th>Metric</th>
      <th>Stream</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @daily_histograms.each do |daily_histogram| %>
      <tr>
        <td><%= daily_histogram.name %></td>
        <td><%= daily_histogram.tweet_count %></td>
        <td><%= daily_histogram.since_id %></td>
        <td><%= daily_histogram.histogram %></td>
        <td><%= daily_histogram.metric %></td>
        <td><%= daily_histogram.stream %></td>
        <td><%= link_to 'Show', daily_histogram %></td>
        <td><%= link_to 'Edit', edit_daily_histogram_path(daily_histogram) %></td>
        <td><%= link_to 'Destroy', daily_histogram, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Daily histogram', new_daily_histogram_path %>

app/views/daily_histograms/new.html.erb
<h1>New daily_histogram</h1>

<%= render 'form' %>

<%= link_to 'Back', daily_histograms_path %>

app/views/daily_histograms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @daily_histogram.name %>
</p>

<p>
  <strong>Tweet count:</strong>
  <%= @daily_histogram.tweet_count %>
</p>

<p>
  <strong>Since:</strong>
  <%= @daily_histogram.since_id %>
</p>

<p>
  <strong>Histogram:</strong>
  <%= @daily_histogram.histogram %>
</p>

<p>
  <strong>Metric:</strong>
  <%= @daily_histogram.metric %>
</p>

<p>
  <strong>Stream:</strong>
  <%= @daily_histogram.stream %>
</p>

<%= link_to 'Edit', edit_daily_histogram_path(@daily_histogram) %> |
<%= link_to 'Back', daily_histograms_path %>